### ISSUE TITLE
NPE in org.femtoframework.coin.spec.element.MapElement

### ISSUE THREAD

**Issue by shaoxt** [femtoframework/femto-util#2]
java.lang.NullPointerException
	at org.femtoframework.lang.reflect.Reflection.isNonStructureClass(Reflection.java:411)
	at org.femtoframework.bean.info.BeanInfoFactory.getBeanInfo(BeanInfoFactory.java:16)
	at org.femtoframework.bean.info.BeanInfoUtil.getBeanInfo(BeanInfoUtil.java:24)
	at org.femtoframework.coin.spec.element.MapElement.getValue(MapElement.java:94)
	at org.femtoframework.coin.spec.element.ListElement.getValue(ListElement.java:94)
	at org.femtoframework.coin.spec.MapSpec.getValue(MapSpec.java:42)
	at org.femtoframework.coin.spec.MapSpec.getValue(MapSpec.java:36)
	at org.bolango.galaxy.htcp.spec.HTcpSpecLoader.toBackendSpec(HTcpSpecLoader.java:109)
	at org.bolango.galaxy.htcp.spec.HTcpSpecLoader.loadSpecs(HTcpSpecLoader.java:72)
	at org.bolango.galaxy.htcp.spec.HTcpSpecLoaderTest.loadSpecs(HTcpSpecLoaderTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by shaoxt** [comment]
Moved it to femto-coin
